# Generated by Django 4.2 on 2023-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = False

    dependencies = [ ('arrangement', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='User_establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'good'),('2','bad')], max_length=1)),
                ('phone', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100))
            ],
        ),
    ]
