# Generated by Django 4.2 on 2023-04-27 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_establishment',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user_establishment',
            name='category',
            field=models.CharField(choices=[('c', 'cafe'), ('r', 'restaurant'), ('p', 'pub')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user_establishment',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user_establishment',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_created=datetime.datetime(2023, 4, 27, 21, 9, 40, 593594))),
                ('passport_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sp', 'sport'), ('tr', 'traveling'), ('pt', 'painting'), ('cg', 'computer_games'), ('sh', 'shoping'), ('ph', 'photo'), ('ms', 'music')], max_length=2)),
                ('user', models.ManyToManyField(to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.user_establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Arrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.user_establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='hobby',
            field=models.ManyToManyField(to='arrangement.hobbies'),
        ),
    ]
