# Generated by Django 4.2 on 2023-05-04 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0005_alter_passport_date_create_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 4, 23, 23, 32, 994046)),
        ),
    ]
