# Generated by Django 4.2 on 2023-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0006_alter_passport_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
