# Generated by Django 4.2 on 2023-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0007_alter_passport_date_create'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['age', 'name'], name='arrangement_age_d35502_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name'], name='arrangement_name_9dbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-name'], name='arrangement_name_4310b3_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['age'], name='arrangement_age_19c875_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['-age'], name='arrangement_age_e19a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['name', '-sex'], name='arrangement_name_198699_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['age', 'sex'], name='arrangement_age_7aaaab_idx'),
        ),
    ]
