# Generated by Django 4.2 on 2023-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0008_users_arrangement_age_d35502_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Приглашающие'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_d35502_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_9dbcdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_4310b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_19c875_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_e19a8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_198699_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_7aaaab_idx',
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(default='Minsk', max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
    ]
